import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {
  forwardRef,
  Box,
  Flex,
  Heading,
  Text,
  Code,
  BoxProps,
} from '@chakra-ui/react'

interface CardProps extends BoxProps {
  sign: string
  href: string
  title: string
  description: string
}

const Card = forwardRef<CardProps, 'div'>((props, ref) => (
  <Box
    m="1rem"
    p="1.5rem"
    textAlign="left"
    color="inherit"
    ref={ref}
    _hover={{
      color: '#0070f3',
      borderColor: '#0070f3',
    }}
    {...props}
  >
    <Heading as="h2" fontSize="1.5rem" mb="1rem">
      {props.title} {props.sign}
    </Heading>
    <Text m={0} fontSize="1.25rem" lineHeight={1.5}>
      {props.description}
    </Text>
  </Box>
))

const cards = [
  {
    href: 'https://nextjs.org/docs',
    title: 'Documentation',
    description: 'Find in-depth information about Next.js features and API.',
  },
  {
    href: 'https://nextjs.org/learn',
    title: 'Learn',
    description: 'Learn about Next.js in an interactive course with quizzes!',
  },
  {
    href: 'https://github.com/vercel/next.js/tree/canary/examples',
    title: 'Examples',
    description: 'Discover and deploy boilerplate example Next.js projects.',
  },
  {
    href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    title: 'Deploy',
    description:
      'Instantly deploy your Next.js site to a public URL with Vercel.',
  },
]

const Home: NextPage = () => {
  return (
    <Box px="2rem">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        as="main"
        direction="column"
        flex={1}
        justifyContent="center"
        alignItems="center"
        minH="100vh"
        py="4rem"
      >
        <Heading
          as="h1"
          margin={0}
          lineHeight={1.15}
          fontSize="4rem"
          textAlign="center"
          sx={{
            '& a': { color: '#0070f3' },
            '& a:hover,focus,active': { textDecoration: 'underline' },
          }}
        >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>

        <Text textAlign="center" my="4rem" lineHeight={1.5} fontSize="1.5rem">
          Get started by editing
          <Code
            bg="#fafafa"
            borderRadius="5px"
            p="0.75rem"
            fontSize="1.1rem"
            fontFamily=""
          >
            pages/index.tsx
          </Code>
        </Text>

        <Flex
          direction={{ base: 'column', md: 'row' }}
          alignItems="center"
          justifyContent="center"
          flexWrap="wrap"
          maxW="800px"
        >
          {cards.map((props) => (
            <Card
              key={props.title}
              as="a"
              sign="&rarr;"
              m="1rem"
              p="1.5rem"
              textAlign="left"
              color="inherit"
              border="1px solid #eaeaea"
              borderRadius="10px"
              transition="color 0.15s ease, border-color 0.15s ease"
              maxW="300px"
              {...props}
            />
          ))}
        </Flex>
      </Flex>

      <Flex
        as="footer"
        flex="1"
        py="2rem"
        borderTop="1px solid #eaeaea"
        alignItems="center"
        justifyContent="center"
        sx={{
          '& a': {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexGrow: 1,
          },
        }}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Box h="1em" ml="0.5rem">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Box>
        </a>
      </Flex>
    </Box>
  )
}

export default Home
